import { ProductType } from '../../types/product';

const products: ProductType[] = [
  {
    id: 523,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: [
      'https://th.bing.com/th/id/R.c3b0363e9f1d13d682acd64a6bd175a6?rik=2t4oWpX3IfSQZA&pid=ImgRaw&r=0',
    ],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 524,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 525,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 526,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 527,
    title: '212',
    price: 212,
    description: 'A description',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 528,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 529,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 530,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 523,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: [
      'https://th.bing.com/th/id/R.c3b0363e9f1d13d682acd64a6bd175a6?rik=2t4oWpX3IfSQZA&pid=ImgRaw&r=0',
    ],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 524,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 525,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 526,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 527,
    title: '212',
    price: 212,
    description: 'A description',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 528,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 529,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 530,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 531,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: [
      'https://th.bing.com/th/id/R.c3b0363e9f1d13d682acd64a6bd175a6?rik=2t4oWpX3IfSQZA&pid=ImgRaw&r=0',
    ],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 532,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 533,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 534,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 535,
    title: '212',
    price: 212,
    description: 'A description',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 536,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 537,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 538,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 539,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 540,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 541,
    title: '212',
    price: 212,
    description: 'A description',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 542,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 543,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
  {
    id: 544,
    title: 'New Bicycle Fuji',
    price: 1000,
    description: 'A description of bicycle',
    images: ['https://placeimg.com/640/480/any'],
    category: {
      id: 1,
      name: 'Test category',
      image: 'https://picsum.photos/640/640?r=1389',
    },
  },
];

export default products;
